### ISSUE TITLE
Can't figure it out

### ISSUE THREAD

**Issue by Gamne** [Allexin/XInput_Blocker#1]
Hello Allexin, I've been trying to get this working so I can use the controller to play games in SteamVR Home on my Oculus Rift S without the buttons and stick affecting my camera

I followed the install instructions and downloaded the .dlls and put them in the Oculus Folder you said but the xbox controller is still being recognised by the Oculus. Any help would be appreciated.

**Comment by Gamne** [comment]
I'm pretty clueless when it comes to all this stuff so I wasn't sure if the files you've provided should just work or if I have to make them myself

**Comment by Allexin** [comment]
Hi, i am provide simple video with full process:
https://www.youtube.com/watch?v=10uc_rELoyg
